
language: objective-c

before_install:
- gem install cocoapods

script:
- cd Demo
- pod repo update --silent
- pod install
- xctool -workspace ConsoleDemo.xcworkspace -scheme 'ConsoleDemo' -configuration Release -sdk iphonesimulator -arch i386 build
